<?php require 'templates/header.php'; ?>

<h1 style="text-align: center; color: rgb(255, 177, 109); font-family: 'Luckiest Guy', cursive; font-size: 40px">Personal Statement</h1>

<hr width="40%" color="rbg(3, 57, 82)">

<p style="margin: 10px; padding: 25px 30px; background-color: rgba(182, 169, 152, 0.15); border-radius: 30px; color: rgb(210, 190, 170); font-size: 17px; font-family: candara">
I have always been a very creative person – both in terms of imagination and creating things – which is what led to getting my degree in Mechanical Engineering, and there I was introduced to coding in a couple of my modules. While the focus of my course was around designing, developing, and manufacturing physical products to satisfy customer wants and needs, the brief experience I gained of coding demonstrated the versatility and scope of even a basic coding program. As such, when I came across the AWS re/Start programme, I was immediately drawn to it and thought of it as a supplement to my degree, as well as opening the door for a much greater range of possible projects. I have always appreciated the power of technology and have occasionally used it to improve both my personal and professional life, but this course opened my eyes to the sheer magnitude of possibilities related to coding and cloud computing.<br></br>

Though Python was my favourite topic that was covered on the AWS re/Start course, I have really enjoyed getting familiar with Ruby, HTML and even CSS since then by making a self-hosted blog and customising the style sheets. I am currently progressing on my front-end development skills even further by building and updating my portfolio website from scratch using PHP: a general purpose scripting language that is suited to web development, but allows for functions and automation generally associated with back-end programming. I am a fast learner, persistent and results driven which means I quickly pick up and build understanding of any new languages and concepts that will help me reach my goal, and I learn from my mistakes rather than being defeated by them. One of my favourite things about programming is that there is no single correct way to do or solve anything, and I appreciate the open and sharing mindset of the community.<br></br>

I enjoy finding my own creative solutions to problems by breaking them down and experimenting with logical steps and, when appropriate, I prefer adopting my own approach rather than implementing existing procedures. The way I naturally think and work lines up well with standard DevOps practices and mentalities: for example, when writing and testing a program or script I am constantly thinking about what I can tweak, add or remove to make the overall user experience better and improve the versatility. Due to my dynamic approach and fondness of experimenting I prefer to tackle tasks individually, but I also enjoy working in a team on large projects where I can be part of a collaborative workflow. My previous experiences at university, with Simple Green Energy and on the AWS programme show that I am an excellent team player and also a capable leader. I am able to maintain respect in a lead role while being empathetic and understanding towards my team; which often gives me further insight into how to direct members to better utilise their individual skills and qualities.<br></br>

My long-term career ambition is to build my own tech consultancy, combining my computer knowledge and experience with my engineering background. To achieve this, I am keen to continue my journey in the tech industry as a Full Stack Developer within a company where I can use and develop the skills I already have, as well as building my knowledge and understanding about the industry.</p>

<hr width="40%" color="rbg(3, 57, 82)">

<?php include 'templates/footer.php'; ?>
</html>